flayo/urls.py
from django.contrib import admin
from django.urls import path, re_path

from homepage.views import UserLoginView, UserRegisterView, CompanyRegisterView, logout_view, SearchJobHomepageView
from homepage.ajax import get_position, get_city
from joboffers.views import OfferAddView, OffersListView, OfferDetailsView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',
         SearchJobHomepageView.as_view(), name="homepage-view"),
    path('add-offer/',
         OfferAddView.as_view(), name="offer-add-view"),
    path('offer/<int:pk>/', OfferDetailsView.as_view(), name='offer_details'),

    path('login/',
         UserLoginView.as_view(), name="login-view"),
    path('signupu/',
         UserRegisterView.as_view(), name="signupu-view"),
    path('signupc/',
         CompanyRegisterView.as_view(), name="signupc-view"),
    path('offers-list/',
         OffersListView.as_view(), name="offers-list-view"),
    path('logout/',
         logout_view, name="logout-view"),
    re_path(r'^api/get_position/', get_position, name='get_position'),
    re_path(r'^api/get_city/', get_city, name='get_city'),

]

joboffers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class City(models.Model):
    city = models.CharField(max_length=64)

    def __str__(self):
        return self.city


class Certificate(models.Model):
    certificate = models.CharField(max_length=64)

    def __str__(self):
        return self.certificate


class Offer(models.Model):

    # Employment statuses
    CONTRACT_WITH_NO_PERIOD = "CONTRACT WITH NO PERIOD"
    CONTRACT_WITH_PERIOD = "Employment contract for a specified period/fixed term"
    B2B = "B2B agreement"
    CONTRACT_FOR_SPECIFIC = "Project delivery contract"

    EMPLOYMENT_STATUSES_CHOICES = (
        (CONTRACT_WITH_NO_PERIOD, _('Employment contract for an unspecified period')),
        (CONTRACT_WITH_PERIOD, _('Employment contract for a specified period/fixed term')),
        (B2B, _('B2B agreement')),
        (CONTRACT_FOR_SPECIFIC, _('Project delivery contract'))
    )

    # Education level
    PRIMARY = 'Primary education'
    SECONDARY = 'Secondary education'
    HIGHER_EDUCATION = 'Higher education'

    EDUCATION_LEVEL_CHOICES = (
        (PRIMARY, _('Primary education')),
        (SECONDARY, _('Secondary education')),
        (HIGHER_EDUCATION, _('Higher education'))
    )

    # basic informations
    position = models.CharField(max_length=64)
    # location
    city = models.ForeignKey(City, on_delete=models.PROTECT, null=True)
    # offer description
    description = models.CharField(max_length=9000, null=True)
    # salaries info
    salary_from = models.IntegerField(null=True, blank=True)
    salary_to = models.IntegerField(null=True, blank=True)
    wage_per_hour_from = models.IntegerField(null=True, blank=True)
    wage_per_hour_to = models.IntegerField(null=True, blank=True)
    employment_status = models.CharField(max_length=64, choices=EMPLOYMENT_STATUSES_CHOICES,
                                         default=CONTRACT_WITH_NO_PERIOD, null=True, blank=True)
    # working_hours = models.CharField(max_length=64, null=True, blank=True)
    # requirements
    requirements = models.CharField(max_length=9000, null=True, blank=True)
    # benefits
    benefits_description = models.CharField(max_length=9000, null=True, blank=True)
    # company
    company_description = models.CharField(max_length=9000, null=True, blank=True)
    company_name = models.CharField(max_length=128, null=True, blank=True)

    # additional informations
    required_docs = models.CharField(max_length=64, null=True, blank=True)
    clause = models.CharField(max_length=512, null=True, blank=True)
    ref_number = models.CharField(max_length=64, null=True, blank=True)
    contact_email = models.CharField(max_length=64, null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(
        _("Created at"),
        auto_now_add=True,
        help_text=_("When offer was created")
    )

    def __str__(self):
        return self.position

#
# class Category(models.Model):
#     name = models.CharField(max_length=64, blank=False)
#
#     def __str__(self):
#         return self.name
#
#
# class Subcategory(models.Model):
#     category = models.ForeignKey(Category, on_delete=models.CASCADE)
#     name = models.CharField(max_length=64, blank=False)
#
#     def __str__(self):
#         return self.name

joboffers/forms.py
from django import forms
from django.urls import reverse, reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab
from crispy_forms.layout import  Submit, Fieldset, Layout, Div
from django.utils.translation import ugettext_lazy as _
from .models import Offer


# JOBS
class OfferAddForm(forms.ModelForm):

    description = forms.CharField(
        label="Please, describe your job offer",
        required=True,
        widget=forms.Textarea()
    )

    salary_from = forms.IntegerField(
        required=False,
    )

    salary_to = forms.IntegerField(
        required=False,
    )

    wage_per_hour_from = forms.IntegerField(
        required=False,
    )

    wage_per_hour_to = forms.IntegerField(
        required=False,
    )

    requirements = forms.CharField(
        label="Please, describe your requirements",
        required=True,
        widget=forms.Textarea()
    )

    class Meta:
        model = Offer
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput
    }


class OffersSearchForm(forms.Form):
    position = forms.CharField(required=False)
    city = forms.CharField(required=False)

joboffers/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404

from django.utils import timezone
from django.views import View
from .models import Offer
from .forms import OfferAddForm, OffersSearchForm

class OfferAddView(LoginRequiredMixin, CreateView):
    login_url = '/login'

    model = Offer
    form_class = OfferAddForm
    template_name = 'offer_add.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return redirect('/')


# BROWSE OFFERS VIEW
class OffersListView(FormView):

    template_name = 'offers_list.html'
    form_class = OffersSearchForm

    def get_context_data(self, **kwargs):
        """Get view context dictionary."""
        context = super(OffersListView, self).get_context_data(**kwargs)
        context['offers_list'] = Offer.objects.all().order_by('-id')
        context['new'] = False
        return context

    def form_valid(self, form):
        position = form.cleaned_data['position']
        city = form.cleaned_data['city']
        offers_list = Offer.objects.filter(city__city__icontains=city).filter(position__icontains=position)
        return render(self.request, 'offers_list.html', {

            'offers_list': offers_list,
            'given_position': position,
            'given_city': city
        })


# OFFER DETAIL VIEW
class OfferDetailsView(DetailView):

    model = Offer

    def get_context_data(self, **kwargs):
        context = super(OfferDetailsView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    def render_to_response(self, context, **response_kwargs):
        """
        Return a response, using the `response_class` for this view, with a
        template rendered with the given context.
        Pass response_kwargs to the constructor of the response class.
        """
        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            request=self.request,
            template='offer_details.html',
            context=context,
            using=self.template_engine,
            **response_kwargs
        )

joboffers/templates/offer_add.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_script %}
<script type="text/javascript" src="{% static 'bootstrap/js/pages/wizard_stepy.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/plugins/forms/wizards/stepy.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/plugins/forms/selects/select2.min.js' %}"></script>

<script type="text/javascript" src="{% static 'bootstrap/js/core/app.js' %}"></script>

<script type="text/javascript" src="{% static 'assets/js/core/app.js' %}"></script>

{% endblock %}


{% block content %}

<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Basic setup -->
            <div class="panel panel-white">
                <div class="panel-heading">
                    <h6 class="panel-title">Basic information</h6>
                </div>
                <form action="" method="post" class="stepy-basic">{% csrf_token %}
                    <fieldset title="1" style="padding-top: 50px">
                        <legend class="text-semibold">Basic information</legend>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Position title:</label>
                                    <input type="text" name="position" id="id_position" class="form-control" placeholder="eg. Python Web Developer">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="form-group">
                                        <label>Company name:</label>
                                        <input type="text" name="company_name" id="id_company_name" class="form-control" placeholder="eg. Google Inc.">
                                    </div>
                                </div>
                            </div>


                            <div class="row">

                                <div class="col-md-6">
                                    <div class="form-group" style="padding-left: 10px">
                                        <label>Select city:</label>
                                        {% include 'partials/input_select_with_tooltip.html' with field=form.city %}
                                    </div>

                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Employment status:</label>
                                        {% include 'partials/input_select_with_tooltip.html' with field=form.employment_status %}
                                    </div>
                                </div>


                            </div>

                            <div class="row">


                                                                    <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="form-group" style="padding-left: 10px">
                                            <label>Contact email:</label>
                                            <input type="text" name="contact_email" id="id_contact_email" class="form-control" placeholder="Contact email for candidates">
                                        </div>
                                    </div>
                                </div>


                            </div>


                    </fieldset>

                    <fieldset title="2" style="padding-top: 50px">
                        <legend class="text-semibold">Job details</legend>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Description:</label>
                                    <textarea name="description" id="id_description" rows="4" cols="4" placeholder="Tasks and responsibilities" class="form-control"></textarea>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Requirements:</label>
                                    <textarea name="requirements" id="id_requirements" rows="4" cols="4" placeholder="Tasks and responsibilities" class="form-control"></textarea>
                                </div>
                            </div>

                        </div>

                    </fieldset>

                    <fieldset title="3" style="padding-top: 50px">
                        <legend class="text-semibold">Company information</legend>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Benefits description:</label>
                                    <textarea name="benefits_description" id="id_benefits_description" rows="4" cols="4" placeholder="Tasks and responsibilities" class="form-control"></textarea>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Company description:</label>
                                    <textarea name="company_description" id="id_company_description" rows="4" cols="4" placeholder="Tasks and responsibilities" class="form-control"></textarea>
                                </div>
                            </div>

                        </div>

                    </fieldset>

                    <fieldset title="4" style="padding-top: 50px">
                        <legend class="text-semibold">Additional info</legend>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Required documents:</label>
                                    <input type="text" name="required_docs" id="id_required_docs" class="form-control" placeholder="eg. CV, motivation list">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Reference number:</label>
                                    <input type="text" name="ref_number" maxlength="64" id="id_ref_number" class="form-control">
                                </div>
                            </div>
                        </div>

                        <div class="row">

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Additional info/Clause:</label>
                                    <textarea name="clause" id="id_clause" rows="5" cols="5" placeholder="If you want to add any info, do it here." class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <button type="submit" class="btn btn-primary stepy-finish">Submit <i class="icon-check position-right"></i></button>
                </form>
                </div>

                {% endblock %}

joboffers/templates/offer_details.html
{% extends 'base.html' %}


{% block content %}


	<!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

			<!-- Main content -->
			<div class="content-wrapper">

				<!-- Detailed task -->
				<div class="row">
					<div class="col-lg-9">

						<!-- Task overview -->
						<div class="panel panel-flat">
							<div class="panel-heading mt-5">
								<h5 class="panel-title">{{ object.position }}</h5>
								<div class="heading-elements">
                                    <h4>{% if object.salary_from and object.salary_to %}
                                        {{ object.salary_from }} - {{ object.salary_to }} ZŁ BRUTTO
                                    {% endif %}
                                    {% if object.wage_per_hour_from and object.wage_per_hour_to %}
                                        {{ object.wage_per_hour_from }} - {{ object.wage_per_hour_from }} ZŁ/H
                                    {% endif %}
                                    </h4>
			                	</div>
							</div>

							<div class="panel-body">
								<h6 class="text-semibold">Opis oferty</h6>
								<p class="content-group">{{ object.description }}</p>

								<h6 class="text-semibold">Wymagania</h6>
								<p class="content-group-lg">{{ object.requirements }}</p>

                                <h6 class="text-semibold">Benefity</h6>
								<p class="content-group-lg">{{ object.benefits_description }}</p>

                                <h6 class="text-semibold">O firmie</h6>
								<p class="content-group-lg">{{ object.company_description }}</p>



							</div>

					    	<div class="panel-footer">
								<div class="heading-elements">
									<ul class="list-inline list-inline-condensed heading-text">
										<li></span> Utworzone: {{ object.created_at }}</li>
									</ul>

									<ul class="list-inline list-inline-condensed heading-text pull-right">
										<li><a href="#" class="text-default"><i class="icon-compose"></i></a></li>
										<li><a href="#" class="text-default"><i class="icon-trash"></i></a></li>
										<li class="dropdown">
											<a href="#" class="text-default dropdown-toggle" data-toggle="dropdown"><i class="icon-grid-alt"></i> <span class="caret"></span></a>
											<ul class="dropdown-menu dropdown-menu-right">
												<li><a href="#"><i class="icon-alarm-add"></i> Check in</a></li>
												<li><a href="#"><i class="icon-attachment"></i> Attach screenshot</a></li>
												<li><a href="#"><i class="icon-user-plus"></i> Assign users</a></li>
												<li><a href="#"><i class="icon-warning2"></i> Report</a></li>
											</ul>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<!-- /task overview -->


					</div>

					<div class="col-lg-3">


						<!-- Task details -->
						<div class="panel panel-flat">
							<div class="panel-heading">
								<h6 class="panel-title"><i class="icon-files-empty position-left"></i> Offer details</h6>
								<div class="heading-elements">
									<ul class="icons-list">
				                		<li><a data-action="collapse"></a></li>
				                		<li><a data-action="reload"></a></li>
				                		<li><a data-action="close"></a></li>
				                	</ul>
			                	</div>
							</div>

							<table class="table table-borderless table-xs content-group-sm">
								<tbody>
                                    <tr>
										<td><i class="icon-history position-left"></i>Company:</td>
										<td class="text-right">{{ object.company_name }}</td>
									</tr>
									<tr>
										<td><i class="icon-briefcase position-left"></i> Miejsce pracy:</td>
										<td class="text-right"><span class="pull-right"><a href="#">{{ object.city }}, {{ object.country }}</a></span></td>
									</tr>
									<tr>
										<td><i class="icon-alarm-add position-left"></i> Status zatrudnienia:</td>
										<td class="text-right">{{ object.employment_status }}</td>
									</tr>
									<tr>
										<td><i class="icon-file-plus position-left"></i> Added by:</td>
										<td class="text-right"><a href="#">Winnie</a></td>
									</tr>
									<tr>
										<td><i class="icon-file-check position-left"></i> Status:</td>
										<td class="text-right">Published</td>
									</tr>
								</tbody>
							</table>

						</div>
						<!-- /task details -->





{% endblock %}

joboffers/templates/offers_list.html
{% extends 'base.html' %}

{% block extra_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

{% endblock %}

{% block content %}

<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main sidebar -->
        <div class="sidebar sidebar-main sidebar-default sidebar-separate">
            <div class="sidebar-content">

                <!-- Sidebar search -->
                <div class="panel panel-white">
                    <div class="panel-heading">
                        <div class="panel-title text-semibold">
                            <i class="icon-search4 text-size-base position-left"></i> Filter
                        </div>
                    </div>

                    <div class="panel-body">
                        <form action="" method="POST"> {% csrf_token %}
                            <div class="form-group">
                                <div class="has-feedback has-feedback-left">
                                    <div class="ui-widget">
                                        <input type="search" class="form-control" name="position" id="id_position" value="{{ given_position }}" placeholder="eg. Python Developer">
                                    </div>
                                    <div class="form-control-feedback">
                                        <i class="icon-reading text-size-large text-muted"></i>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="has-feedback has-feedback-left">
                                    <div class="ui-widget">
                                        <input type="search" class="form-control" name="city" id="id_city" value="{{ given_city }}" placeholder="eg. Warsaw">
                                    </div>
                                    <div class="form-control-feedback">
                                        <i class="icon-pin-alt text-size-large text-muted"></i>
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="btn bg-blue btn-block">
                                <i class="icon-search4 text-size-base position-left"></i> Find jobs
                            </button>
                        </form>
                    </div>
                </div>
                <!-- /sidebar search -->

            </div>
        </div>
        <!-- /main sidebar -->

        <!-- Main content -->
        <div class="content-wrapper">
            {% for offer in offers_list %}
            <!-- Cards layout -->
            <ul class="media-list content-group">
                <li class="media panel panel-body stack-media-on-mobile">
                    <div class="media-left">
                        <a href="#">
                            <img src="assets/images/placeholder.jpg" class="img-rounded img-lg" alt="">
                        </a>
                    </div>

                    <div class="media-body">
                        <h6 class="media-heading text-semibold">
								<a href="{% url 'offer_details' offer.pk %}">{{ offer.position }}</a>
							</h6>

                        <ul class="list-inline list-inline-separate text-muted mb-10">
                            <li><a href="#" class="text-muted">{{ offer.company_name }}</a></li>
                            <li>{{ offer.city }}, {{ offer.country }}</li>
                        </ul>

                        Extended kindness trifling remember he confined outlived if. Assistance sentiments yet unpleasing say. Open they an busy they my such high. An active dinner wishes at unable hardly no talked on. Immediate him her resolving his favourite. Wished denote abroad at branch at. Mind what no by kept.
                    </div>

                    <div class="media-right text-nowrap">
                        <span class="label bg-blue">New</span>
                    </div>
                </li>

            </ul>
            {% endfor %}
            <!-- /cards layout -->

            <!-- Pagination -->
            <div class="text-center content-group-lg pt-20">
                <ul class="pagination">
                    <li class="disabled"><a href="#"><i class="icon-arrow-small-left"></i></a></li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#"><i class="icon-arrow-small-right"></i></a></li>
                </ul>
            </div>
            <!-- /pagination -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>

{% endblock %} {% block extra_js %}
<script>
    $(document).ready(function() {
        var location_input = $('input[id="id_position"]');
        location_input.autocomplete({
            source: "/api/get_position/",
            minLength: 2
        });
    });

    //   keeps same width as box
    jQuery.ui.autocomplete.prototype._resizeMenu = function() {
        var ul = this.menu.element;
        ul.outerWidth(this.element.outerWidth());
    }
</script>

<script>
    $(document).ready(function() {
        var location_input = $('input[id="id_city"]');
        location_input.autocomplete({
            source: "/api/get_city/",
            minLength: 2
        });
    });

    //   keeps same width as box
    jQuery.ui.autocomplete.prototype._resizeMenu = function() {
        var ul = this.menu.element;
        ul.outerWidth(this.element.outerWidth());
    }
</script>

{% endblock %}