flayo/urls.py
from django.contrib import admin
from django.urls import path, re_path

from homepage.views import UserLoginView, UserRegisterView, CompanyRegisterView, logout_view, SearchJobHomepageView
from homepage.ajax import get_position, get_city
from joboffers.views import OfferAddView, OffersListView, OfferDetailsView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',
         SearchJobHomepageView.as_view(), name="homepage-view"),
    path('add-offer/',
         OfferAddView.as_view(), name="offer-add-view"),
    path('offer/<int:pk>/', OfferDetailsView.as_view(), name='offer_details'),

    path('login/',
         UserLoginView.as_view(), name="login-view"),
    path('signupu/',
         UserRegisterView.as_view(), name="signupu-view"),
    path('signupc/',
         CompanyRegisterView.as_view(), name="signupc-view"),
    path('offers-list/',
         OffersListView.as_view(), name="offers-list-view"),
    path('logout/',
         logout_view, name="logout-view"),
    re_path(r'^api/get_position/', get_position, name='get_position'),
    re_path(r'^api/get_city/', get_city, name='get_city'),

]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User


class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.TextField()

homepage/forms.py
from django import forms
from django.core.exceptions	import ValidationError
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab
from crispy_forms.layout import  Submit, Fieldset, Layout, Div
from django.contrib.auth.models import User
from joboffers.models import Offer


#    LOGIN

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


#    REGISTER


class UserRegisterForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField()
    email_confirm = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [

            'username',
            'email',
            'email_confirm',
            'password',
            'password_confirm'

                  ]

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-user-register-form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Register', css_class='btn-success'))
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Fieldset('Log in',
                      Field('username', css_class="some-class"),
                      Field('email', css_class="some-class"),
                      Field('email_confirm', css_class="some-class"),
                      Field('password', css_class="some-class"),
                      Field('password_confirm', css_class="some-class")),
        )

    def clean(self):
        print(self.cleaned_data)

        email = self.cleaned_data['email']
        email_confirm = self.cleaned_data['email_confirm']

        if email != email_confirm:
            raise forms.ValidationError("Emails must match")

        password = self.cleaned_data['password']
        password_confirm = self.cleaned_data['password_confirm']

        if password != password_confirm:
            raise forms.ValidationError("Passwords must match")

        return self.cleaned_data


class CompanyRegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    email_confirm = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)
    company_name = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(CompanyRegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-company-register-form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Register', css_class='btn-success'))
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Fieldset('Log in',
                      Field('username', css_class="some-class"),
                      Field('email', css_class="some-class"),
                      Field('email_confirm', css_class="some-class"),
                      Field('password', css_class="some-class"),
                      Field('password_confirm', css_class="some-class"),
                      Field('company_name', css_class="some-class")),
        )

    def clean(self):
        print(self.cleaned_data)

        email = self.cleaned_data['email']
        email_confirm = self.cleaned_data['email_confirm']

        if email != email_confirm:
            raise forms.ValidationError("Emails must match")

        password = self.cleaned_data['password']
        password_confirm = self.cleaned_data['password_confirm']

        if password != password_confirm:
            raise forms.ValidationError("Passwords must match")

        return self.cleaned_data


class OffersSearchForm(forms.Form):
    position = forms.CharField(required=False)
    city = forms.CharField(required=False)

homepage/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.db import IntegrityError
from django.forms.utils import ErrorList
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth import (authenticate,
                                 login,
                                 logout,
                                 )
from django.contrib import messages
from django.contrib.auth.models import User, Permission, Group
import json
from .forms import UserLoginForm, UserRegisterForm, CompanyRegisterForm, OffersSearchForm
from .models import Company
from joboffers.models import Offer



def logout_view(request):
    logout(request)
    return redirect('/')


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {

            'form': form
        })

    def post(self, request):
        fail = 'Wrong username or password'
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, "Incorrect credentials")

        return render(request, self.template_name, {

            'form': form,
            'fail': fail
        })


# User register
class UserRegisterView(FormView):
    form_class = UserRegisterForm
    template_name = 'user_register.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        try:
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # Employee group adding
            group = Group.objects.get(name="user")
            user.groups.add(group)
            user.save()
            return redirect('/login')
        except IntegrityError:
            form._errors['username'] = ErrorList(['Username "{}" is already in use'.format(username)])

            return super(UserRegisterView, self).form_invalid(form)


#  Company register
class CompanyRegisterView(FormView):
    form_class = CompanyRegisterForm
    template_name = 'company_register.html'

    def form_valid(self, form):
        try:

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            company_name = form.cleaned_data['company_name']
            user = User(username=username, email=email, )
            user.set_password(password)
            user.save()
            employer = Company(user=user, company_name=company_name)
            employer.save()
            # Employee group adding
            group = Group.objects.get(name="company")
            user.groups.add(group)
            user.save()
            return redirect('/login')
        except IntegrityError:
            form._errors['username'] = ErrorList(['Username "{}" is already in use'.format(username)])

        return super(CompanyRegisterView, self).form_invalid(form)


class SearchJobHomepageView(FormView):
    template_name = 'homepage.html'
    form_class = OffersSearchForm

    def form_valid(self, form):
        position = form.cleaned_data['position']
        city = form.cleaned_data['city']
        offers_list = Offer.objects.filter(city__city__icontains=city).filter(position__icontains=position)
        return render(self.request, 'offers_list.html', {

            'offers_list': offers_list,
            'given_position': position,
            'given_city': city
        })

homepage/templates/base.html
{% load static %}
{% load user_has_group %}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="{% static 'bootstrap/css/icons/icomoon/styles.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'bootstrap/css/core.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'bootstrap/css/components.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'bootstrap/css/colors.css' %}" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script type="text/javascript" src="{% static 'bootstrap/js/plugins/loaders/pace.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap/js/core/libraries/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap/js/core/libraries/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap/js/plugins/loaders/blockui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap/js/plugins/ui/nicescroll.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/plugins/ui/drilldown.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap/js/plugins/ui/fab.min.js' %}"></script>
	<!-- /core JS files -->
    {% block extra_script %}

    {% endblock %}
</head>
<body>

<body class="navbar-bottom login-container">

	<!-- Page header -->
	<div class="page-header page-header-inverse">

		<!-- Main navbar -->
		<div class="navbar navbar-inverse navbar-transparent">
			<div class="navbar-header">
				<a class="navbar-brand" href="/"><img src="{% static 'bootstrap/images/logo_light.png' %}" alt=""></a>

				<ul class="nav navbar-nav pull-right visible-xs-block">
					<li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-grid3"></i></a></li>
					<li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
				</ul>
			</div>

			<div class="navbar-collapse collapse" id="navbar-mobile">
				<div class="navbar-right">
					<ul class="nav navbar-nav">
                        {% if request.user|user_has_group:"company" %}
                        <li><a href="/offers-list">Browse offers</a></li>
                        <li><a href="/add-offer">Post a job</a></li>
                        {% elif request.user|user_has_group:"user" %}
                        <li><a href="/offers-list">Browse offers</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
						<li class="dropdown dropdown-user">
							<a class="dropdown-toggle" data-toggle="dropdown">
								<img src="{% static 'bootstrap/images/placeholder.jpg' %}" alt="">
								<span>{{ user.username}} </span>
								<i class="caret"></i>
							</a>

							<ul class="dropdown-menu dropdown-menu-right">
								<li><a href="#"><i class="icon-user-plus"></i> My profile</a></li>
								<li><a href="#"><i class="icon-coins"></i> My balance</a></li>
								<li><a href="#"><span class="badge bg-blue pull-right">26</span> <i class="icon-comment-discussion"></i> Messages</a></li>
								<li class="divider"></li>
								<li><a href="#"><i class="icon-cog5"></i> Account settings</a></li>
								<li><a href="/logout"><i class="icon-switch2"></i> Logout</a></li>
							</ul>
						</li>
                        {% else %}
                        					<li><a href="{% url 'signupu-view' %}">Sign up User</a></li>
                                            <li><a href="{% url 'signupc-view' %}">Sign up Company</a></li>
                                            <li><a href="{% url 'login-view' %}">Log in</a></li>

                        {% endif %}

					</ul>
				</div>
			</div>
		</div>
    </div>
		<!-- /main navbar -->

{% block content %}

{% endblock %}

{% block extra_js %}

{% endblock %}


</body>
</html>

homepage/templates/company_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


	<!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

			<!-- Main content -->
			<div class="content-wrapper">

				<!-- Registration form -->
				<form action="" method="POST"> {% csrf_token %}
                                        {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger col-lg-6 col-lg-offset-3">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger col-lg-6 col-lg-offset-3">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
					<div class="row">
						<div class="col-lg-6 col-lg-offset-3">
							<div class="panel">
								<div class="panel-body">
									<div class="text-center">
										<div class="icon-object border-success text-success"><i class="icon-plus3"></i></div>
                                        <h5 class="content-group-lg">Create <b>company</b> account <small class="display-block">All fields are required</small></h5>
									</div>

									<div class="form-group has-feedback">
										<input type="text" name="username" id="id_username" class="form-control" placeholder="Choose username" required>
										<div class="form-control-feedback">
											<i class="icon-user-plus text-muted"></i>
										</div>
									</div>

									<div class="row">
										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="password" class="form-control" placeholder="Create password" name="password" id="id_password" required>
												<div class="form-control-feedback">
													<i class="icon-user-lock text-muted"></i>
												</div>
											</div>
										</div>

										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="password" class="form-control" placeholder="Repeat password" name="password_confirm" id="id_password_confirm" required>
												<div class="form-control-feedback">
													<i class="icon-user-lock text-muted"></i>
												</div>
											</div>
										</div>
									</div>

									<div class="row">
										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="email" name="email" id="id_email" class="form-control" placeholder="Your email" required>
												<div class="form-control-feedback">
													<i class="icon-mention text-muted"></i>
												</div>
											</div>
										</div>

										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="email" name="email_confirm" id="id_email_confirm" class="form-control" placeholder="Repeat email" required>
												<div class="form-control-feedback">
													<i class="icon-mention text-muted"></i>
												</div>
											</div>
										</div>
									</div>

                                    <div class="row">
										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="text" name="company_name" id="id_company_name" class="form-control" placeholder="Your company name" required>
												<div class="form-control-feedback">
													<i class="icon-home4 text-muted"></i>
												</div>
											</div>
										</div>

									</div>

									<div class="form-group">

									</div>

									<div class="clearfix">
										<a href="{% url 'login-view' %}" class="btn btn-default pull-left"><i class="icon-arrow-left13 position-left"></i> Back to login form</a>
										<button type="submit" class="btn bg-pink-400 btn-labeled btn-labeled-right pull-right"><b><i class="icon-plus3"></i></b> Create account</button>
									</div>
								</div>
							</div>
						</div>
					</div>

				</form>
				<!-- /registration form -->

			</div>
			<!-- /main content -->

		</div>
		<!-- /page content -->

	</div>
	<!-- /page container -->





{% endblock %}

homepage/templates/homepage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_script %}
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

{% endblock %}

{% block content %}

<form action="" method="POST"> {% csrf_token %}
    <div class="ui-widget">
        <input type="text" name="position" id="id_position" placeholder="eg. Python Developer" />
    </div>
    <input type="text" name="city" id="id_city" placeholder="eg. Warsaw" />

    <input type="submit" value="Search" />
</form>

{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function() {
        var location_input = $('input[id="id_position"]');
        location_input.autocomplete({
            source: "/api/get_position/",
            minLength: 2
        });
    });

    //   keeps same width as box
    jQuery.ui.autocomplete.prototype._resizeMenu = function() {
        var ul = this.menu.element;
        ul.outerWidth(this.element.outerWidth());
    }
</script>

<script>
    $(document).ready(function() {
        var location_input = $('input[id="id_city"]');
        location_input.autocomplete({
            source: "/api/get_city/",
            minLength: 2
        });
    });

    //   keeps same width as box
    jQuery.ui.autocomplete.prototype._resizeMenu = function() {
        var ul = this.menu.element;
        ul.outerWidth(this.element.outerWidth());
    }
</script>
{% endblock %}

homepage/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">
            <form action="" method="post" class="login-form">
                <div class="panel panel-body">
                    <div class="text-center">
                        <div class="icon-object border-slate-300 text-slate-300"><i class="icon-reading"></i></div>
                        <h5 class="content-group">Login to your account <small class="display-block">Enter your credentials below</small></h5>
                    </div>
                    {% csrf_token %}
                    <div class="form-group has-feedback has-feedback-left">
                        <input type="text" class="form-control" placeholder="Username" name="username" id="id_username">
                        <div class="form-control-feedback">
                            <i class="icon-user text-muted"></i>
                        </div>
                    </div>

                    <div class="form-group has-feedback has-feedback-left">
                        <input type="password" class="form-control" placeholder="Password" name="password" id="id_password">
                        <div class="form-control-feedback">
                            <i class="icon-lock2 text-muted"></i>
                        </div>
                    </div>
                    <div class="login-errors">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                              {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn bg-pink-400 btn-block">Sign in <i class="icon-circle-right2 position-right"></i></button>
                    </div>

                    <div class="text-center">
                        <a href="login_password_recover.html">Forgot password?</a>
                    </div>
                </div>

            </form>
        </div>
        <!-- /main content -->

    <!-- /page content -->

</div>

{% endblock %}

homepage/templates/user_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

			<!-- Main content -->
			<div class="content-wrapper">

				<!-- Registration form -->
				<form action="" method="POST"> {% csrf_token %}
                                        {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger col-lg-6 col-lg-offset-3">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger col-lg-6 col-lg-offset-3">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
					<div class="row">
						<div class="col-lg-6 col-lg-offset-3">
							<div class="panel">
								<div class="panel-body">
									<div class="text-center">
										<div class="icon-object border-success text-success"><i class="icon-plus3"></i></div>
										<h5 class="content-group-lg">Create <b>user</b> account <small class="display-block">All fields are required</small></h5>
									</div>

									<div class="form-group has-feedback">
										<input type="text" name="username" id="id_username" class="form-control" placeholder="Choose username" required>
										<div class="form-control-feedback">
											<i class="icon-user-plus text-muted"></i>
										</div>
									</div>

									<div class="row">
										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="password" class="form-control" placeholder="Create password" name="password" id="id_password" required>
												<div class="form-control-feedback">
													<i class="icon-user-lock text-muted"></i>
												</div>
											</div>
										</div>

										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="password" class="form-control" placeholder="Repeat password" name="password_confirm" id="id_password_confirm" required>
												<div class="form-control-feedback">
													<i class="icon-user-lock text-muted"></i>
												</div>
											</div>
										</div>
									</div>

									<div class="row">
										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="email" name="email" id="id_email" class="form-control" placeholder="Your email" required>
												<div class="form-control-feedback">
													<i class="icon-mention text-muted"></i>
												</div>
											</div>
										</div>

										<div class="col-md-6">
											<div class="form-group has-feedback">
												<input type="email" name="email_confirm" id="id_email_confirm" class="form-control" placeholder="Repeat email" required>
												<div class="form-control-feedback">
													<i class="icon-mention text-muted"></i>
												</div>
											</div>
										</div>
									</div>

									<div class="form-group">

									</div>

									<div class="clearfix">
										<a href="{% url 'login-view' %}" class="btn btn-default pull-left"><i class="icon-arrow-left13 position-left"></i> Back to login form</a>
										<button type="submit" class="btn bg-pink-400 btn-labeled btn-labeled-right pull-right"><b><i class="icon-plus3"></i></b> Create account</button>
									</div>
								</div>
							</div>
						</div>
					</div>

				</form>
				<!-- /registration form -->

			</div>
			<!-- /main content -->

		</div>
		<!-- /page content -->

	</div>
	<!-- /page container -->






{% endblock %}